# Development Dockerfile for Vite
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./package*.json ./

RUN npm install

# Copy source files
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Start the Vite dev server
CMD ["npm", "run", "dev"]
