version: "3.8"

services:
  shortener:
    build: ./shortener
    container_name: shortener
    env_file:
      - .env
      - ./shortener/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  redirector:
    build: ./redirector
    container_name: redirector
    env_file:
      - .env
      - ./redirector/.env
    ports:
      - "8082:8082"

  nginx:
    build: ./nginx
    container_name: nginx-gateway
    ports:
      - "8080:80"
    depends_on:
      - shortener
      - redirector

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
