version: "3.8"

services:
  shortener:
    build: ./shortener
    container_name: shortener
    ports:
      - "8081:8080"

  redirector:
    build: ./redirector
    container_name: redirector
    ports:
      - "8082:8080"

  nginx:
    build: ./nginx
    container_name: nginx-gateway
    ports:
      - "8080:80"
    depends_on:
      - shortener
      - redirector
